### ISSUE TITLE
Upload failing with stressed characters in song name and deduplication api enabled

### ISSUE THREAD

**Issue by thunder2k** [jaymoulin/google-music-manager-uploader#3]
Hi,
I have a song with à char in song name. I've enabled your deduplication API running with docker.

When it tries to check if that file exists, the following error is returned and the uploader crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 334, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/google-music-upload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 192, in main
    deduplicate_api=args.deduplicate_api
  File "/usr/local/lib/python3.5/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 136, in upload
    upload_file(api, file_path, logger, remove=remove, deduplicate_api=deduplicate)
  File "/usr/local/lib/python3.5/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 83, in upload_file
    exists = deduplicate_api.exists(file_path)
  File "/usr/local/lib/python3.5/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 27, in exists
    result = requests.request('GET', self.uri + "/", data={"path": file_path})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by jaymoulin** [comment]
Should be fixed by https://github.com/jaymoulin/google-musicmanager-dedup-api/commit/d41379ab53997c94749c6057a73778d0b525bc49

**Comment by thunder2k** [comment]
> Should be fixed by [jaymoulin/google-musicmanager-dedup-api@d41379a](https://github.com/jaymoulin/google-musicmanager-dedup-api/commit/d41379ab53997c94749c6057a73778d0b525bc49)

How can I update the docker image? I've run the command from the readme but it doesn't seem to have it updated or, if it did, the fix doesn't work
