### ISSUE TITLE
Oauth error

### ISSUE THREAD

**Issue by wingnut144** [jaymoulin/google-music-manager-uploader#9]
Version Number: 1.6.1

**Description**

When running the command:   google-music-upload --oauth /tmp/oauth --directory /mnt/music/                                              

I'm getting:
```
completed
2020-03-30 18:44:36,443 - google_music_manager_uploader.uploader_daemon - INFO -                                               Init Daemon - Press Ctrl+C to quit
2020-03-30 18:44:37,094 - gmusicapi.Manager1 (musicmanager:139) [ERROR]: upauth                                               failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/shared.py", li                                              ne 245, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/musicmanager.p                                              y", line 96, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 9                                              : MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/clients/musicmanager.py                                              ", line 133, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/clients/shared.py", lin                                              e 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/shared.py", li                                              ne 259, in perform
    raise CallFailure(err_msg, e.callname) from e
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Up                                              load auth error code 9: MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more info                                              rmation.
(requests kwargs: {'method': 'POST', 'url': 'https://android.clients.google.com/                                              upsj/upauth', 'data': b'\n\x11B8:27:EB:7F:B6:86\x12\x1aTorrent (gmusicapi-13.0.0                                              )', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)',                                               'Authorization': '<omitted>'}})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 à](\x000\x80}8\x00H\x01P\x                                              01X\t`\x00j\x13\n\x11B8:27:EB:7F:B6:86')
Traceback (most recent call last):
  File "/usr/local/bin/google-music-upload", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/google_music_manager_uploader/upl                                              oader_daemon.py", line 200, in main
    deduplicate_api=args.deduplicate_api,
  File "/usr/local/lib/python3.7/dist-packages/google_music_manager_uploader/upl                                              oader_daemon.py", line 127, in upload
    raise ValueError("Error with oauth credentials")
ValueError: Error with oauth credentials
```

**Steps to reproduce the issue:**
1.  Double check to make sure all libraries have been added
2.  Reboot device
3.  Regenerated a oauth file

**Describe the results you received:**
Listed above

**Describe the results you expected:**
That the script would run without the error message :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by wingnut144** [comment]
I can send you a copy of the oauth contents if that would help as well

**Comment by wingnut144** [comment]
In doing some digging around, I removed the 2FA from my Google account, and got a completely different OAUTH file created.  The new file is referenced in the command:

google-music-upload --oauth /tmp/oauthgoogle-music-auth --directory /mnt/music/completed

But I'm still getting:

```
2020-03-30 22:07:18,882 - google_music_manager_uploader.uploader_daemon - INFO - Init Daemon - Press Ctrl+C to quit
2020-03-30 22:07:19,575 - gmusicapi.Manager1 (musicmanager:139) [ERROR]: upauth failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/shared.py", line 245, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/musicmanager.py", line 96, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 9: MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/clients/musicmanager.py", line 133, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/shared.py", line 259, in perform
    raise CallFailure(err_msg, e.callname) from e
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 9: MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more information.
(requests kwargs: {'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth', 'data': b'\n\x11B8:27:EB:7F:B6:86\x12\x1aTorrent (gmusicapi-13.0.0)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)', 'Authorization': '<omitted>'}})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 à](\x000\x80}8\x00H\x01P\x01X\t`\x00j\x13\n\x11B8:27:EB:7F:B6:86')
Traceback (most recent call last):
  File "/usr/local/bin/google-music-upload", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 200, in main
    deduplicate_api=args.deduplicate_api,
  File "/usr/local/lib/python3.7/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 127, in upload
    raise ValueError("Error with oauth credentials")
ValueError: Error with oauth credentials
```

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

Looks like you used all available slots for your Google Music Account. Please make sure you did not reach the maximum allowed devices (10) on this link https://play.google.com/music/listen?u=0#/accountsettings under the `Devices` section. 
If not, remove some unused devices. Be very careful with your oauth file as generating a new one will create a new device and Google limits the number of removable device a year.

**Comment by wingnut144** [comment]
I did check for the number of devices, and I only have 2 listed.  I haven't noticed that generating a new oauth file has been generating a new device.  I've been at 2 for a while

These are the only 2 devices that it lists:
Verizon Wireless Device
Last accessed: March 21, 2020

Computer App
Last accessed: March 9, 2020

**Comment by jaymoulin** [comment]
I noticed your oauth file is stored in `/tmp` directory. As `/tmp` is a special directory automatically cleaned in most actual OS, I suggest you store this file in a more persistent path (such as `$HOME`. which should be default one).

By using the described process and paths in the README file, you should have a more stable behaviour.
1. google-music-auth "$HOME/oauth"
1. google-music-upload --oauth "$HOME/oauth" --directory /mnt/music/completed

**Comment by wingnut144** [comment]
Ok, tried the new path like you suggested:

```
google-music-upload --oauth "$HOME/oauth" --directory /mnt/music/completed
2020-04-01 17:27:07,800 - google_music_manager_uploader.uploader_daemon - INFO - Init Daemon - Press Ctrl+C to quit
2020-04-01 17:27:08,466 - gmusicapi.Manager1 (musicmanager:139) [ERROR]: upauth failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/shared.py", line 245, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/musicmanager.py", line 96, in check_success
    ), cls.__name__
gmusicapi.exceptions.CallFailure: AuthenticateUploader: Upload auth error code 9: MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more information. 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/clients/musicmanager.py", line 133, in _perform_upauth
    uploader_name)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gmusicapi/protocol/shared.py", line 259, in perform
    raise CallFailure(err_msg, e.callname) from e
gmusicapi.exceptions.CallFailure: AuthenticateUploader: AuthenticateUploader: Upload auth error code 9: MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more information. 
(requests kwargs: {'method': 'POST', 'url': 'https://android.clients.google.com/upsj/upauth', 'data': b'\n\x11B8:27:EB:7F:B6:86\x12\x1aTorrent (gmusicapi-13.0.0)', 'headers': {'User-agent': 'Music Manager (1, 0, 55, 7425 HTTPS - W
indows)', 'Authorization': '<omitted>'}})
(response was: '\x08\x062\x14\x08\x00\x10\x00\x18\x05 à](\x000\x80}8\x00H\x01P\x01X\t`\x00j\x13\n\x11B8:27:EB:7F:B6:86')
Traceback (most recent call last):
  File "/usr/local/bin/google-music-upload", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 200, in main
    deduplicate_api=args.deduplicate_api,
  File "/usr/local/lib/python3.7/dist-packages/google_music_manager_uploader/uploader_daemon.py", line 127, in upload
    raise ValueError("Error with oauth credentials")
ValueError: Error with oauth credentials
```

**Comment by wingnut144** [comment]
Does it matter what account this is being run from?  Does it have to be root?

**Comment by jaymoulin** [comment]
You don't have to be root but the problem you're facing is related with your oauth file and the allowed devices on your Google Music account. You may also need to change your `UPLOADER_ID` parameter to avoid any possible conflict (`--uploader_id UPLOADER_ID` parameter)

**Comment by wingnut144** [comment]
Well it turns out it WAS a issue with Google Music.....not sure what they did, I still only show 2 devices, but its working now.

Quick question, do you know what the command would be to get this to start with Crontab?  I'm trying 
@reboot /home/pi/.local/bin/google-music-upload --oauth "$HOME/oauth" --directory /mnt/music/completed 2>&1

But its just not starting.......appreciate all your help, I'll contribute for sure, system works well :)

**Comment by jaymoulin** [comment]
I'm not really sure on how it works for reboot but some environment variables may not be ready on reboot. Here are some suggestion to make it work:

1. call the google-music-upload binary with your python full path and home full path `@reboot /usr/bin/python3  /home/pi/.local/bin/google-music-upload --oauth "/home/pi/oauth" --directory /mnt/music/completed 2>&1`
1. check your crontab logs for hints `tail /var/log/cron.log`

P.S. Thank you for your donation, this is really helping <3

**Comment by wingnut144** [comment]
Can you clarify what the --remove command does?  The description says
"remove files if present", but can you tell me what that means?  Does it
delete from a directory after upload?  Before??

Thanks :)

**Comment by jaymoulin** [comment]
`--remove` will remove the file on your hard drive if it was already successfully uploaded (either because it's already on your Google Music library or after a successful upload)

Closing the issue as it seems resolved
